//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _7637_WS4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_7637_WS4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check boards using the test unit of printed circuit boards (PCB).
        /// </summary>
        internal static string comment_BPPP {
            get {
                return ResourceManager.GetString("comment_BPPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control unit check.
        /// </summary>
        internal static string comment_BU {
            get {
                return ResourceManager.GetString("comment_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror unit check.
        /// </summary>
        internal static string comment_BZ {
            get {
                return ResourceManager.GetString("comment_BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the top panel select the tested item.
        /// </summary>
        internal static string comment_ListBoards_Initial {
            get {
                return ResourceManager.GetString("comment_ListBoards_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the left panel select the tested board.
        /// </summary>
        internal static string comment_ListBpppBoards_Initial {
            get {
                return ResourceManager.GetString("comment_ListBpppBoards_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select desired type of test.
        /// </summary>
        internal static string comment_ListBU_Initial {
            get {
                return ResourceManager.GetString("comment_ListBU_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version of mirror unit to check.
        /// </summary>
        internal static string comment_ListBZ_Initial {
            get {
                return ResourceManager.GetString("comment_ListBZ_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control the frequency and amplitude of the signals Up 1, Up 1 L, Uop 2, Uop 2 L on the oscilloscope. Switch them with the help of toggle switches of the transition unit. V1 = 22.7±2 V, V2 = 16.1±2 V.  f=400±10 Hz.
        /// </summary>
        internal static string comment_OSC_Test {
            get {
                return ResourceManager.GetString("comment_OSC_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the circuit boards using the test signal unit.
        /// </summary>
        internal static string comment_PP {
            get {
                return ResourceManager.GetString("comment_PP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ListBoardsInitImage {
            get {
                object obj = ResourceManager.GetObject("ListBoardsInitImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ListBpppBoardInitmage {
            get {
                object obj = ResourceManager.GetObject("ListBpppBoardInitmage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_big {
            get {
                object obj = ResourceManager.GetObject("logo_big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pict_BPPP {
            get {
                object obj = ResourceManager.GetObject("pict_BPPP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pict_BU {
            get {
                object obj = ResourceManager.GetObject("pict_BU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pict_BZ {
            get {
                object obj = ResourceManager.GetObject("pict_BZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pict_PP {
            get {
                object obj = ResourceManager.GetObject("pict_PP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pictLoadError {
            get {
                object obj = ResourceManager.GetObject("pictLoadError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
